services:
  web:
    build:
      context: .
      args:
        ENV: dev # o prod
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
