# Generated by Django 5.0.7 on 2025-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'efectivo'), ('tarjeta', 'tarjeta'), ('transferencia', 'transferencia'), ('otro', 'otro')], default='efectivo', max_length=64),
        ),
    ]
