# Generated by Django 5.0.7 on 2025-09-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_pago_metodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='referencia',
            new_name='evidencia_s3',
        ),
    ]
