# Generated by Django 5.0.7 on 2025-09-25 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_referencia_pago_evidencia_s3'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='reservations.reserva'),
        ),
    ]
