# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cargo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagocargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
