# Generated by Django 5.0.7 on 2025-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cargo_created_at_alter_pago_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagocargo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
