# Generated by Django 5.0.7 on 2025-09-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_cargo_is_deleted_pago_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='evidencia_s3',
            new_name='comprobante_key',
        ),
    ]
