# Generated by Django 5.0.7 on 2025-09-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_rename_evidencia_s3_pago_comprobante_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
