# Generated by Django 5.0.7 on 2025-09-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_cargo_deleted_at_cargo_deleted_by_pago_deleted_at_and_more'),
        ('reservations', '0005_areacomun_deleted_at_areacomun_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='reservations.reserva'),
        ),
    ]
