# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_cargo_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pagocargo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pagocargo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='pagocargo',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='cargo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagocargo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
