# Generated by Django 5.0.7 on 2025-09-30 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0011_remove_cargo_deleted_at_remove_cargo_deleted_by_and_more'),
        ('housing', '0015_rename_direccion_principal_condominio_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='pagocargo',
            name='orden',
        ),
        migrations.AddField(
            model_name='cargo',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='cargo',
            index=models.Index(fields=['unidad', 'concepto', 'estado', 'periodo'], name='finance_car_unidad__1247f4_idx'),
        ),
    ]
