# Generated by Django 5.0.7 on 2025-09-30 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_cargo_reserva_remove_pagocargo_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='monto_total',
        ),
        migrations.AlterField(
            model_name='pagocargo',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
