# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
