# Generated by Django 5.0.7 on 2025-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_areacomun_created_at_alter_reserva_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
