# Generated by Django 5.0.7 on 2025-09-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_areacomun_is_deleted_reserva_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasuministro',
            name='devuelto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservasuministro',
            name='entregado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservations.areacomun'),
        ),
    ]
