# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_areacomun_deleted_at_areacomun_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='areacomun',
            name='reservation_is_acti_0898af_idx',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('finalizada', 'finalizada'), ('cancelada', 'cancelada')], default='pendiente', max_length=16),
        ),
        migrations.AddIndex(
            model_name='areacomun',
            index=models.Index(fields=['name'], name='reservation_name_a03733_idx'),
        ),
    ]
