# Generated by Django 5.0.7 on 2025-09-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_areacomun_reservation_is_acti_0898af_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suministro',
            old_name='nombre',
            new_name='name',
        ),
    ]
