# Generated by Django 5.0.7 on 2025-09-30 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_suministro_created_at_suministro_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='requires_deposit',
        ),
        migrations.AddField(
            model_name='areacomun',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='suministro',
            name='areacomun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='reservations.areacomun'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReservaSuministro',
        ),
    ]
