# Generated by Django 5.2.6 on 2025-09-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.unidad'),
        ),
    ]
