# Generated by Django 5.0.7 on 2025-09-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rol_unidad'),
        ('housing', '0002_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_document',
            new_name='document_id',
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together={('user', 'group_name', 'unidad')},
        ),
    ]
