# Generated by Django 5.0.7 on 2025-09-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_id_document_customuser_document_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='rol',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.rol'),
        ),
        migrations.RemoveField(
            model_name='rol',
            name='user',
        ),
    ]
