# Generated by Django 5.0.7 on 2025-09-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_group_name_rol_name_alter_rol_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='unidad',
        ),
    ]
