# Generated by Django 5.0.7 on 2025-09-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_rol_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='document_id',
            new_name='CI',
        ),
    ]
