# Generated by Django 5.0.7 on 2025-09-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_document_id_customuser_ci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='CI',
            new_name='ci',
        ),
    ]
