# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_ci_customuser_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
