# Generated by Django 5.0.7 on 2025-09-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_created_at_alter_rol_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
