# Generated by Django 5.0.7 on 2025-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
