# Generated by Django 5.0.7 on 2025-09-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_photo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
