# Generated by Django 5.0.7 on 2025-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_deleted_at_customuser_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Soft delete lógico, distinto de is_deleted de TimeStampedBy'),
        ),
    ]
