# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_es_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='es_activo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
    ]
