# Generated by Django 5.0.7 on 2025-09-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('deuda', 'deuda'), ('multa', 'multa'), ('evento', 'evento'), ('otro', 'otro')], max_length=32),
        ),
    ]
