# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
