# Generated by Django 5.0.7 on 2025-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_comunicado_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('deuda', 'deuda'), ('multa', 'multa'), ('evento', 'evento'), ('comunicado', 'comunicado'), ('otro', 'otro')], max_length=32),
        ),
    ]
