# Generated by Django 5.0.7 on 2025-09-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_comunicado_deleted_at_comunicado_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='comunicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='communication.comunicado'),
        ),
    ]
