# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_alter_notificacion_comunicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='comunicado',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
