# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_visita_vehiculo_acceso_user_acceso_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
