# Generated by Django 5.0.7 on 2025-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_acceso_created_at_alter_incidente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidente',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
