# Generated by Django 5.0.7 on 2025-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_acceso_is_deleted_incidente_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceso',
            old_name='evidencia_s3',
            new_name='evidencia_key',
        ),
        migrations.AddField(
            model_name='visita',
            name='photo_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
