# Generated by Django 5.0.7 on 2025-09-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_rename_evidencia_s3_acceso_evidencia_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='evidencia_key',
        ),
        migrations.AddField(
            model_name='acceso',
            name='evidencia_s3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='acceso',
            name='match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceso',
            name='permitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='modo',
            field=models.CharField(choices=[('manual', 'manual'), ('face', 'face'), ('placas', 'placas')], default='manual', max_length=16),
        ),
    ]
