# Generated by Django 5.0.7 on 2025-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_contrato_is_deleted_mascota_is_deleted_and_more'),
        ('security', '0006_remove_acceso_evidencia_key_acceso_evidencia_s3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modo', models.CharField(choices=[('manual', 'manual'), ('face', 'face'), ('placa', 'placa')], max_length=16)),
                ('tipo', models.CharField(choices=[('usuario', 'usuario'), ('externo', 'externo'), ('vehiculo', 'vehiculo')], max_length=16)),
                ('match', models.BooleanField(default=False)),
                ('evidencia_s3', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='acceso',
            name='security_ac_unidad__d87e7e_idx',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='evidencia_s3',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='match',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='modo',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='user',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='visita',
        ),
        migrations.AlterField(
            model_name='visita',
            name='photo_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='acceso',
            index=models.Index(fields=['unidad', 'created_at'], name='security_ac_unidad__be97e4_idx'),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='security.acceso'),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.vehiculo'),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.visita'),
        ),
    ]
