# Generated by Django 5.0.7 on 2025-09-28 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_acceso_deleted_at_acceso_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='visita',
            constraint=models.UniqueConstraint(fields=('documento', 'user'), name='unique_visita_por_user'),
        ),
    ]
