# Generated by Django 5.0.7 on 2025-09-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_visita_unique_visita_por_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='visita',
            name='unique_visita_por_user',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='user',
        ),
        migrations.AddField(
            model_name='visita',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marca si la visita está activa o desactivada (soft delete)'),
        ),
    ]
