# Generated by Django 5.0.7 on 2025-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_remove_visita_unique_visita_por_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='Soft delete lógico, distinto de is_deleted de TimeStampedBy'),
        ),
    ]
