# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_visita_es_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='accesoevidencia',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='accesoevidencia',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='accesoevidencia',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='es_activo',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='acceso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accesoevidencia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
