# Generated by Django 5.0.7 on 2025-09-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_remove_acceso_deleted_at_remove_acceso_deleted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='visita',
            name='documento',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
