# Generated by Django 5.0.7 on 2025-09-25 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0006_rename_fecha_fin_contrato_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=160)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='maintenance.servicio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'abierto'), ('en_progreso', 'en_progreso'), ('resuelto', 'resuelto'), ('cerrado', 'cerrado')], default='abierto', max_length=16)),
                ('programado', models.DateTimeField(blank=True, null=True)),
                ('cerrado', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.servicio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_mant', to='housing.unidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['is_active', 'name'], name='maintenance_is_acti_50fbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifaservicio',
            index=models.Index(fields=['servicio', 'vigente_desde', 'vigente_hasta'], name='maintenance_servici_f31f50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifaservicio',
            unique_together={('servicio', 'vigente_desde')},
        ),
        migrations.AddIndex(
            model_name='ticketmantenimiento',
            index=models.Index(fields=['unidad', 'estado'], name='maintenance_unidad__2cfb79_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmantenimiento',
            index=models.Index(fields=['programado'], name='maintenance_program_b1fc05_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmantenimiento',
            index=models.Index(fields=['cerrado'], name='maintenance_cerrado_92d8d9_idx'),
        ),
    ]
