# Generated by Django 5.0.7 on 2025-09-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_servicio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarifaservicio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
