# Generated by Django 5.0.7 on 2025-09-29 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_servicio_deleted_at_servicio_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmantenimiento',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='maintenance.servicio'),
        ),
    ]
