# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_ticketmantenimiento_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tarifaservicio',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tarifaservicio',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tarifaservicio',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ticketmantenimiento',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ticketmantenimiento',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ticketmantenimiento',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='tarifaservicio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
