# Generated by Django 5.0.7 on 2025-09-30 09:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_remove_servicio_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmantenimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketmantenimiento',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='maintenance.servicio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TarifaServicio',
        ),
    ]
