# Generated by Django 5.0.7 on 2025-09-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_unidad_user_vehiculo_anio_vehiculo_user_contrato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='user',
            new_name='responsable',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='user',
        ),
        migrations.AddField(
            model_name='mascota',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residency',
            name='status',
            field=models.CharField(choices=[('activa', 'activa'), ('inactiva', 'inactiva')], default='activa', max_length=16),
        ),
        migrations.AddField(
            model_name='residency',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('propietario', 'propietario'), ('inquilino', 'inquilino')], default='propietario', max_length=16),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='residency',
            unique_together={('user', 'unidad', 'start')},
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['unidad', 'inquilino', 'is_active'], name='housing_con_unidad__fcd535_idx'),
        ),
        migrations.AddIndex(
            model_name='residency',
            index=models.Index(fields=['unidad', 'user', 'status'], name='housing_res_unidad__4dd975_idx'),
        ),
    ]
