# Generated by Django 5.0.7 on 2025-09-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_rename_user_vehiculo_responsable_remove_mascota_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='observaciones',
            new_name='observacion',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='anio',
        ),
    ]
