# Generated by Django 5.0.7 on 2025-09-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_rename_observaciones_vehiculo_observacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_fin',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_inicio',
            new_name='start',
        ),
    ]
