# Generated by Django 5.0.7 on 2025-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_rename_fecha_fin_contrato_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='residency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
