# Generated by Django 5.0.7 on 2025-09-29 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0010_remove_mascota_unidad_alter_mascota_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residency',
            unique_together={('user', 'unidad')},
        ),
    ]
