# Generated by Django 5.0.7 on 2025-09-29 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0011_alter_residency_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contrato',
            name='housing_con_unidad__fcd535_idx',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='residency',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='residency',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='residency',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='residency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['unidad', 'inquilino'], name='housing_con_unidad__5892ae_idx'),
        ),
    ]
