# Generated by Django 5.0.7 on 2025-09-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0012_remove_contrato_housing_con_unidad__fcd535_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombre',
            new_name='name',
        ),
    ]
