# Generated by Django 5.0.7 on 2025-09-30 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0014_condominio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='direccion_principal',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='unidad',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='housing.condominio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='manzano',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
