# Generated by Django 5.0.7 on 2025-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0015_rename_direccion_principal_condominio_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='tipo_ocupacion',
            field=models.CharField(choices=[('propietario', 'propietario'), ('residente', 'residente')], default='propietario', max_length=16),
        ),
    ]
